
# getting the python image from resin

FROM resin/%%RESIN_MACHINE_NAME%%-python

#Get library to test DHT22


# set work directory
WORKDIR /usr/src/app
COPY . ./
git remote add resin chakhovskoi@git.resin.io:chakhovskoi/pythonbot.git
#systemmd turned on

ENV INITSYSTEM on

CMD ["python","src/main.py"]
