
# getting the python image from resin

FROM resin/%%RESIN_MACHINE_NAME%%-python



# set work directory
WORKDIR /usr/src/app
COPY . ./
#systemmd turned on

ENV INITSYSTEM on

CMD ["python","src/main.py"]
